In [1]:
import pandas as pd

In [2]:
#dataframe 생성
score={'학번':[201524213,201621223,201621233, 201611111, 201722222],
       '이름':['오지환','박용택','정성훈', '다니엘', '지민'],
       '학과':['경영정보','경영정보','경영정보','컴퓨터공학','컴퓨터공학'],
       'Quiz':[15,20,10,17,18],
       '중간고사':[20,20,15,18,16]}

df= pd.DataFrame(score)
df

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
2  201621233  정성훈   경영정보    10    15
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16

In [3]:
#인덱싱 이용하여 학번 추출
df['학번']

0    201524213
1    201621223
2    201621233
3    201611111
4    201722222
Name: 학번, dtype: int64

In [4]:
#인덱싱 이용허여 이름/중간고사 추출
df[['이름', '중간고사']]

이름  중간고사
0  오지환    20
1  박용택    20
2  정성훈    15
3  다니엘    18
4   지민    16

In [5]:
#인덱싱 이용해서 순서 변경
df = df.reindex([2, 0, 4, 1, 3])
df


학번   이름     학과  Quiz  중간고사
2  201621233  정성훈   경영정보    10    15
0  201524213  오지환   경영정보    15    20
4  201722222   지민  컴퓨터공학    18    16
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

In [6]:
#iloc 과 loc을 박용택 기록 추출
print(df.iloc[3])
print(df.loc[1])

학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object
학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object


In [7]:
##iloc 과 loc을 모든 학생의 이름과 중간고사 점수 추출
print(df.iloc[:, [1, 4]])
print(df.loc[:, ['이름', '중간고사']])

    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18
    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18


In [8]:
# 중간고사 평균 추출
df['중간고사'].mean()

17.8

In [9]:
#중간고사 점수가 가장 낮은 학생 추출
df['중간고사'].idxmin()

2

In [10]:
#퀴즈 점수가 가장 높은 학생의 학번 추출
df.loc[df['Quiz'].idxmax(), '학번']
#df.loc[df['Quiz'].idxmax()]['학번']

201621223

In [11]:
df.describe()

학번       Quiz       중간고사
count  5.000000e+00   5.000000   5.000000
mean   2.016200e+08  16.000000  17.800000
std    7.018995e+04   3.807887   2.280351
min    2.015242e+08  10.000000  15.000000
25%    2.016111e+08  15.000000  16.000000
50%    2.016212e+08  17.000000  18.000000
75%    2.016212e+08  18.000000  20.000000
max    2.017222e+08  20.000000  20.000000

In [12]:
df.sort_values('중간고사', ascending=False)

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16
2  201621233  정성훈   경영정보    10    15

In [13]:
quiz_mean = df['Quiz'].mean()
df[df['Quiz'] > quiz_mean]['이름']

4     지민
1    박용택
3    다니엘
Name: 이름, dtype: object

In [14]:
#퀴즈와 중간고사 점수 모두 평균 이상인 학생 기록 추출
quiz_mean = df['Quiz'].mean()
mid_mean = df['중간고사'].mean()
df[(df['Quiz'] > quiz_mean) & (df['중간고사'] > mid_mean)]

학번   이름     학과  Quiz  중간고사
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

In [15]:
# value_counts 이용하여 학과 학생 수 추출
df['학과'].value_counts()

경영정보     3
컴퓨터공학    2
Name: 학과, dtype: int64

In [17]:
#groupby를 이용해서 학과 별로 중간고사 평균 추출
df.groupby('학과')['중간고사'].mean()

학과
경영정보     18.333333
컴퓨터공학    17.000000
Name: 중간고사, dtype: float64

In [18]:
df.mean()

학번      201620000.4
Quiz           16.0
중간고사           17.8
dtype: float64

In [19]:
list(df.groupby('학과'))

[('경영정보',
            학번   이름    학과  Quiz  중간고사
  2  201621233  정성훈  경영정보    10    15
  0  201524213  오지환  경영정보    15    20
  1  201621223  박용택  경영정보    20    20),
 ('컴퓨터공학',
            학번   이름     학과  Quiz  중간고사
  4  201722222   지민  컴퓨터공학    18    16
  3  201611111  다니엘  컴퓨터공학    17    18)]

# Numpy 연습문제

In [21]:
import numpy as np

In [22]:
#np.zeros이용하여 행이 3, 열이 4인 ndarray 생성 
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# a에 대하여 다중 for문을 이용해서 값을 초기화
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [24]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [25]:
# 초기화 된 a에서 7을 꺼냄
a[1, 2]

7.0

In [26]:
# 둘째 행을 추출
a.shape

(3, 4)

In [27]:
a[[1], :]

array([[5., 6., 7., 8.]])

In [28]:
#둘쨰 열과 셋쨰열 추출
a[:,[0, 2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

In [29]:
# a에서 6보다 작거나 같은 값 추출하기 위해 불리안 인덱싱 사용
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [30]:
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

In [32]:
#np,random 패키지를 이용해서 0,1 값이 무작위로 생성된, 행이 3열 4인 ndarray (b) 생성
b = np.random.random((3, 4))
b

array([[0.59769787, 0.85509489, 0.3741418 , 0.13785535],
       [0.4621516 , 0.44280426, 0.77522542, 0.70262432],
       [0.23139222, 0.37883856, 0.86106446, 0.41816188]])

In [33]:
c = a * b
c

array([[0.59769787, 1.71018978, 1.12242539, 0.55142141],
       [2.31075798, 2.65682554, 5.42657791, 5.62099456],
       [2.08253001, 3.78838558, 9.47170909, 5.01794251]])

In [34]:
#b의 전치행렬을 d에 저장
d = b.T
d

array([[0.59769787, 0.4621516 , 0.23139222],
       [0.85509489, 0.44280426, 0.37883856],
       [0.3741418 , 0.77522542, 0.86106446],
       [0.13785535, 0.70262432, 0.41816188]])

In [35]:
d.shape

(4, 3)

In [36]:
# a와 d에 대하여 각 차원의 크기 출력
print(a.shape, d.shape)

(3, 4) (4, 3)


In [37]:
# a와 d의 행렵곱 계산 후 e에 저장
e = a.dot(d)
e

array([[ 3.98173446,  6.48393364,  5.24491023],
       [11.8408941 , 16.01515599, 12.80273871],
       [19.70005375, 25.54637835, 20.3605672 ]])

In [38]:
#e에 대하여 각 열의 합 구함
np.sum(e, axis=1)

array([15.71057833, 40.65878881, 65.6069993 ])