In [11]:
import numpy as np

In [12]:
# ndarray를 사용해보기 전에 비교를 위해 먼저 리스트를 실펴본다.
a = [1, 2, 3, 4, 5, 6]
print(a)
b = [[1, 2, 3], [4, 5, 6]] # 리스트로 2차원 행렬을 표현했을때의 모양
print(b)
c = [1, 'a', 3.5] # 리스트는 서로 다른 type의 데이터 저장이 가능
print(c)

[1, 2, 3, 4, 5, 6]
[[1, 2, 3], [4, 5, 6]]
[1, 'a', 3.5]


In [13]:
a = np.array([1, 2, 3])  # 1차원 배열 생성
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # 배열의 한 원소를 변경
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [14]:
b = np.array([[1,2,3],[4,5,6]])   # 2차원 배열 생성
print(b) #2차원 배열의 모양을 확인

[[1 2 3]
 [4 5 6]]


In [15]:
print(b.shape) #배열의 각 차원의 크기
print(b[0, 0], b[0, 1], b[1, 0]) #인덱싱 예제

(2, 3)
1 2 4


In [16]:
a = np.zeros((2, 3))  # 값이 모두 0인 배열 생성, 매개변수는 원하는 shape
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
b = np.ones((3, 4))   # 값이 모두 1인 배열 생성
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
c = np.full((2, 4), 7) # 모든 원소가 원하는 값으로 초기화된 배열 생성
print(c)

[[7 7 7 7]
 [7 7 7 7]]


In [24]:
d = np.eye(4)        # 2x2의 단위행렬(identity matrix)을 생성
print(d)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
e = np.random.random((2,4)) # 무작위값으로 이루어진 배열 생성
print(e)

[[0.45004818 0.30865016 0.97103662 0.14076831]
 [0.87284831 0.56652506 0.59105806 0.40887184]]


In [21]:
import numpy as np

# shape가 (3, 4)이고 아래와 같은 값을 갖는 2차원 배열을 생성
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 아래와 같은 일부를 뽑아내고 싶다면?
# [[2 3]
#  [6 7]]
#        0열 1열 2열 3열
# 0행 [[ 1   2   3   4]
# 1행  [ 5   6   7   8]
# 2행  [ 9  10  11  12]]

b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [22]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(b)
print(a)

2
[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
c = b.copy()
c[0, 0] = 55
print(c)
print(b)

[[55  3]
 [ 6  7]]
[[77  3]
 [ 6  7]]


In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, a.shape

In [25]:
row_r1 = a[1, :]    # 차원이 감소되는 것에 주의  
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [26]:
row_r2 = a[1:2, :]  # 차원 유지됨
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [27]:
row_r3 = a[2, :]  # 차원 유지됨
print(row_r3, row_r3.shape)

[ 9 10 11 12] (4,)


In [28]:
# 컬럼만 잘라낼 때에도 마찬가지:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


In [29]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a, a.shape)

# 정수 배열 인덱싱의 예.
# 반환된 배열의 shape는 (3,) 
print(a[[0, 1, 2], [0, 1, 0]])

# 위 방식은 아래 방식과 동일한 결과를 만들어 냄:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 4 5]
[1 4 5]


In [30]:
# 정수 배열 인덱싱을 할 때, 같은 요소를 가져오게 될 수도 있음
print(a[[0, 0], [1, 1]])

# 아래 예제와 동일
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [31]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
print(np.arange(4))
print(range(4))

[0 1 2 3]
range(0, 4)


In [33]:
# 정수 배열 선언
b = np.array([0, 2, 0, 1])

# b의 각 행에서 위 배열에 해당하는 열의 값을 가져오고 싶다면?
print(a[np.arange(4), b])

[ 1  6  7 11]


In [34]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [36]:
bb = np.array([1, 2, 3, 4, 5, 6])

# ndarray 중 벡터에 대한 비교연산자 적용 결과
bb > 3

array([False, False, False,  True,  True,  True])

In [37]:
# 벡터에 대한 불리안 인덱싱 결과

bb[bb > 3] # bb 값 중에서 3보다 큰 값만 반환 

array([4, 5, 6])

In [38]:
# 행렬에 대한 불리안 인덱싱 결과 확인
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # 배열의 개별적인 요소에 대해서 2보다 큰지를 True/False 배열로 반환

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [39]:
# 불리안 배열의 값이 true인 요소들만 반환
print(a[bool_idx])

# 아래와 같이 줄여서 사용 가능:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


In [40]:
x = np.array([1, 2])  # 자동으로 타입 선택
y = np.array([1.0, 2.0])  # 자동으로 타입 선택
z = np.array([1, 2], dtype=np.int64)  # 명시적으로 타입을 지정

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


In [41]:
z = np.array([1, 2], dtype=np.float32) #값은 정수인데 타입은 실수로 한 경우
z

array([1., 2.], dtype=float32)

In [42]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [43]:
# 요소합(elementwise sum), 결과로 ndarray를 생성한다
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [44]:
# 요소차(Elementwise difference)
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [45]:
# 요소곱(Elementwise product)
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [46]:
# 요소 나눗셈(Elementwise division)
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [47]:
# Elementwise square root
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x)) #sqrt가 각 요소에 적용됨

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [48]:
import math
a = [1, 2, 3, 4]

math.sqrt(a) #sqrt()가 리스트에도 작동하는지 확인

TypeError: must be real number, not list

In [53]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x, x.shape)
print(y, y.shape)
print(v, v.shape)
print(w, w.shape)

[[1 2]
 [3 4]] (2, 2)
[[5 6]
 [7 8]] (2, 2)
[ 9 10] (2,)
[11 12] (2,)


In [50]:
# 벡터 내적(Inner product)
print(v.dot(w))
print(np.dot(v, w))

219
219


In [51]:
# 행렬과 벡터 간 곱셈(matrix / vector product)
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [52]:
# 행렬 곱셈(Matrix multiplication / product)
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [57]:
x = np.array([[1,2],[3,4]])
print(x)

print(np.sum(x))  # 모든 요소의 합 "10"
print(np.sum(x, axis=0))  # 열(column)의 합을 계산 "[4 6]"
print(np.sum(x, axis=1))  # 행(row)의 합을 계산; prints "[3 7]"

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [55]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [56]:
v = np.array([[1,2,3]])
print(v)
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [58]:
# 벡터 v 를 행렬 x의 모든 행에 더하고자 함,
# 그 결과는 행렬 y에 저장
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print('x =\n', x)
v = np.array([1, 0, 1])
y = np.empty_like(x)   # x와 동일한 shape를 가진 빈 행렬을 생성

# 반복문을 이용해 x의 각 행에 v를 더함
for i in range(4):
    y[i, :] = x[i, :] + v

print('y =\n', y)

x =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
y =
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [59]:
vv = np.tile(v, (4, 1))  # x 행의 수만큼 v를 반복해서 vv를 생성
print(vv)                 # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [60]:
y = x + vv  # x와 vv를 요소합
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [61]:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # x와 v의 shape이 다르기 때문에 자동으로 브로드캐스팅이 작동
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [62]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# 위의 경우, v와 w의 shape이 다르므로 요소곱을 하는 경우 에러가 발생함
# 먼저 v를 열로 바꿔서 shape을 (3, 1)로 만든 후에 브로드캐스팅을 적용하면 v와 w가 (3, 2)로 확장되고
# 그 다음 요소곱을 실행
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [63]:
# 벡터를 행렬의 각 행에 더하고자 하는 경우
x = np.array([[1,2,3], [4,5,6]])
print('x =\n', x)
# x는 (2, 3)이고 v는 (3,)이므로 v를 (2, 3)으로 브로드캐스트

print('result =\n', x + v)

x =
 [[1 2 3]
 [4 5 6]]
result =
 [[2 4 6]
 [5 7 9]]


In [64]:
# x의 각 행에 w를 더하고 싶다면?
# x는 (2, 3), w는 크기가 2인 벡터이므로 차원이 맞지 않음
# w를 reshape해서 (2, 1)로 바꾸면 브로드캐스팅이 가능
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [65]:
# x 행렬에 상수 곱을 하고 싶을 때
# Numpy는 스칼라를 shape ()로 취급;
# 따라서 x에 맞춰 스칼라를 shape (2, 3)으로 브로드캐스팅이 가능
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


# Pandas Tutorial 

In [66]:
import pandas as pd


In [67]:
s = pd.Series([1, 3, 5, 7, 9])
print(s)
print(s[2]) #indexing

0    1
1    3
2    5
3    7
4    9
dtype: int64
5


In [68]:
# dictionary를 이용해 만들기
dic = {'a':1, 'b':3, 'c':5}
s = pd.Series(dic)
print(s)
print(s['b']) #indexing

a    1
b    3
c    5
dtype: int64
3


In [69]:
print(s.values)
print(s.index)

[1 3 5]
Index(['a', 'b', 'c'], dtype='object')


In [70]:
s = pd.Series([1,3,5,7,9], index=['LGT','DOO','HWE','LOT','SKW'])
#print(s)
#print(s['LOT'])
print(s[:'LOT']) # 슬라이싱에서 어디까지 나오는지 주목

LGT    1
DOO    3
HWE    5
LOT    7
dtype: int64


In [71]:
score={'학번':[201524213,201621223,201621233],
       '이름':['오지환','박용택','정성훈'],
       'Quiz':[15,20,10],
       '중간고사':[20,20,15]}

score_df= pd.DataFrame(score)
score_df

학번   이름  Quiz  중간고사
0  201524213  오지환    15    20
1  201621223  박용택    20    20
2  201621233  정성훈    10    15

In [72]:
print(type(score_df['학번']))
score_df['학번']


<class 'pandas.core.series.Series'>


0    201524213
1    201621223
2    201621233
Name: 학번, dtype: int64

In [73]:
d = {
    'Name':['Alisa','Bobby','Cathrine','Madonna','Rocky','Sebastian','Jaqluine',
   'Rahul','David','Andrew','Ajay','Teresa'],
   'Age':[26,27,25,24,31,27,25,33,42,32,51,47],
   'Score':[89,87,67,55,47,72,76,79,44,92,99,69]}
 
df = pd.DataFrame(d)
df

Name  Age  Score
0       Alisa   26     89
1       Bobby   27     87
2    Cathrine   25     67
3     Madonna   24     55
4       Rocky   31     47
5   Sebastian   27     72
6    Jaqluine   25     76
7       Rahul   33     79
8       David   42     44
9      Andrew   32     92
10       Ajay   51     99
11     Teresa   47     69

In [74]:
df['Age']

0     26
1     27
2     25
3     24
4     31
5     27
6     25
7     33
8     42
9     32
10    51
11    47
Name: Age, dtype: int64

In [75]:
type(df['Name'])

pandas.core.series.Series

In [76]:
type(df[['Name']])


pandas.core.frame.DataFrame

In [77]:
df[0:3]  #df[2]는 에러 발생

Name  Age  Score
0     Alisa   26     89
1     Bobby   27     87
2  Cathrine   25     67

In [78]:
df=df.reindex([1,4,6,2,3,5,9,8,0,7,11,10]) # 일부러 순차가 아닌 인덱스를 부여
df


Name  Age  Score
1       Bobby   27     87
4       Rocky   31     47
6    Jaqluine   25     76
2    Cathrine   25     67
3     Madonna   24     55
5   Sebastian   27     72
9      Andrew   32     92
8       David   42     44
0       Alisa   26     89
7       Rahul   33     79
11     Teresa   47     69
10       Ajay   51     99

In [79]:
df.loc[:6]

Name  Age  Score
1     Bobby   27     87
4     Rocky   31     47
6  Jaqluine   25     76

In [80]:
df.iloc[:6]

Name  Age  Score
1      Bobby   27     87
4      Rocky   31     47
6   Jaqluine   25     76
2   Cathrine   25     67
3    Madonna   24     55
5  Sebastian   27     72

In [81]:
# sort the pandas dataframe by index ascending
 
df1=df.sort_index()
df1

Name  Age  Score
0       Alisa   26     89
1       Bobby   27     87
2    Cathrine   25     67
3     Madonna   24     55
4       Rocky   31     47
5   Sebastian   27     72
6    Jaqluine   25     76
7       Rahul   33     79
8       David   42     44
9      Andrew   32     92
10       Ajay   51     99
11     Teresa   47     69

In [82]:
df1.loc[:6]

Name  Age  Score
0      Alisa   26     89
1      Bobby   27     87
2   Cathrine   25     67
3    Madonna   24     55
4      Rocky   31     47
5  Sebastian   27     72
6   Jaqluine   25     76

In [83]:
df1.iloc[:6]

Name  Age  Score
0      Alisa   26     89
1      Bobby   27     87
2   Cathrine   25     67
3    Madonna   24     55
4      Rocky   31     47
5  Sebastian   27     72

In [84]:
# sort the pandas dataframe by index descending
 
df2=df.sort_index(ascending=False)
df2


Name  Age  Score
11     Teresa   47     69
10       Ajay   51     99
9      Andrew   32     92
8       David   42     44
7       Rahul   33     79
6    Jaqluine   25     76
5   Sebastian   27     72
4       Rocky   31     47
3     Madonna   24     55
2    Cathrine   25     67
1       Bobby   27     87
0       Alisa   26     89

In [85]:
df2.iloc[:, 2]

11    69
10    99
9     92
8     44
7     79
6     76
5     72
4     47
3     55
2     67
1     87
0     89
Name: Score, dtype: int64

In [86]:
df2.loc[:, ['Name', 'Age']]

Name  Age
11     Teresa   47
10       Ajay   51
9      Andrew   32
8       David   42
7       Rahul   33
6    Jaqluine   25
5   Sebastian   27
4       Rocky   31
3     Madonna   24
2    Cathrine   25
1       Bobby   27
0       Alisa   26

In [87]:
df2.iloc[:, :2]

Name  Age
11     Teresa   47
10       Ajay   51
9      Andrew   32
8       David   42
7       Rahul   33
6    Jaqluine   25
5   Sebastian   27
4       Rocky   31
3     Madonna   24
2    Cathrine   25
1       Bobby   27
0       Alisa   26

In [88]:
df2.loc[:, :'Age']

Name  Age
11     Teresa   47
10       Ajay   51
9      Andrew   32
8       David   42
7       Rahul   33
6    Jaqluine   25
5   Sebastian   27
4       Rocky   31
3     Madonna   24
2    Cathrine   25
1       Bobby   27
0       Alisa   26

In [106]:
df = pd.read_csv('RegularSeasonCompactResults.csv')

FileNotFoundError: [Errno 2] File RegularSeasonCompactResults.csv does not exist: 'RegularSeasonCompactResults.csv'

In [90]:
df.head()

Name  Age  Score
1     Bobby   27     87
4     Rocky   31     47
6  Jaqluine   25     76
2  Cathrine   25     67
3   Madonna   24     55

In [91]:
df.tail()

Name  Age  Score
8    David   42     44
0    Alisa   26     89
7    Rahul   33     79
11  Teresa   47     69
10    Ajay   51     99

In [98]:
df.shape

(12, 3)

In [99]:
df.columns.tolist()

['Name', 'Age', 'Score']

In [100]:
df.describe()

Age      Score
count  12.000000  12.000000
mean   32.500000  73.000000
std     9.209679  17.653225
min    24.000000  44.000000
25%    25.750000  64.000000
50%    29.000000  74.000000
75%    35.250000  87.500000
max    51.000000  99.000000

In [101]:
df.max()

Name     Teresa
Age          51
Score        99
dtype: object

In [104]:
df['Score'].max()

99

In [105]:
df.loc[24970] #반환된 index 값을 이용해 값을 출력

KeyError: 24970

In [107]:
for index, row in df.iterrows():
    print('#Data type of row:', type(row))
    print(row)
    if index == 1:
        break

#Data type of row: <class 'pandas.core.series.Series'>
Name     Bobby
Age         27
Score       87
Name: 1, dtype: object


In [108]:
df.isnull().sum()

Name     0
Age      0
Score    0
dtype: int64

In [110]:
import matplotlib.pyplot as plt
%matplotlib inline

In [111]:
ax = df['Wscore'].plot.hist(bins=20)
ax.set_xlabel('Points for Winning Team')
plt.show()

KeyError: 'Wscore'

In [112]:
df1.fillna(0).to_csv('test.csv')
df2 = pd.read_csv('test.csv')
df2

Unnamed: 0       Name  Age  Score
0            0      Alisa   26     89
1            1      Bobby   27     87
2            2   Cathrine   25     67
3            3    Madonna   24     55
4            4      Rocky   31     47
5            5  Sebastian   27     72
6            6   Jaqluine   25     76
7            7      Rahul   33     79
8            8      David   42     44
9            9     Andrew   32     92
10          10       Ajay   51     99
11          11     Teresa   47     69

In [113]:
#첫째 방법
df1.fillna(0).to_csv('test.csv', index=False) #인덱스를 저장하지 않음
df2 = pd.read_csv('test.csv')
df2

Name  Age  Score
0       Alisa   26     89
1       Bobby   27     87
2    Cathrine   25     67
3     Madonna   24     55
4       Rocky   31     47
5   Sebastian   27     72
6    Jaqluine   25     76
7       Rahul   33     79
8       David   42     44
9      Andrew   32     92
10       Ajay   51     99
11     Teresa   47     69

In [114]:
#둘째 방법
df1.fillna(0).to_csv('test.csv')
df2 = pd.read_csv('test.csv', index_col=0) #첫 열을 인덱스로 저장
df2

Name  Age  Score
0       Alisa   26     89
1       Bobby   27     87
2    Cathrine   25     67
3     Madonna   24     55
4       Rocky   31     47
5   Sebastian   27     72
6    Jaqluine   25     76
7       Rahul   33     79
8       David   42     44
9      Andrew   32     92
10       Ajay   51     99
11     Teresa   47     69